apiVersion: v1
kind: Service
metadata:
  name: go-mtls-server-service
spec:
  type: NodePort
  selector:
    app: go-mtls-server
  ports:
    - port: {{ .Values.server.servicePort }}
      targetPort: {{ .Values.server.servicePort }}
      nodePort: {{ .Values.server.nodePort }}
