apiVersion: v1
kind: Secret
metadata:
  name: go-mtls-server-certs
type: Opaque
data:
  server.chain.pem: {{ .Values.server.certs.server_chain_pem | b64enc }}
  server.key.pem: {{ .Values.server.certs.server_key_pem | b64enc }}
  root.cert.pem: {{ .Values.server.certs.root_cert_pem | b64enc }}
  intermediate.cert.pem: {{ .Values.server.certs.intermediate_cert_pem | b64enc }}