server:
  hostName: "localhost"
  certBaseDir: "certs"
  certSubDir: "server"
  port: "8443"
  serverRootPath: "/hello"
client:
  hostName: "localhost"
  certBaseDir: "certs"
  certSubDir: "client"
  port: "8443"
  serverRootPath: "/hello"
