# Build stage
FROM golang:1.26-alpine AS builder

WORKDIR /app

COPY . .

# RUN go mod init github.com/sirajudheenam/pki-mtls/pki-go
# RUN go mod tidy

# Build client binary
RUN go build -o client cmd/client/main.go

# Runtime stage
FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/client .
COPY certs ./certs

# CMD ["sh", "-c", "./client --server-name ${SERVER_NAME} --server-port ${SERVER_PORT} --server-root-path ${SERVER_ROOT_PATH} --cert-path ${CERT_PATH}"]

CMD ["./client"]