# Build stage
FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY . .

# Build client binary
RUN go build -o client cmd/client/main.go

# Runtime stage
FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/client .
COPY certs/client ./certs/client

CMD ["./client"]

