# Build stage
FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY . .

# Build client binary
RUN go build -o client cmd/client/main.go

# Runtime stage
FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/client .
COPY certs/client ./certs/client

# CMD ["sh", "-c", "./client --server-name ${SERVER_NAME} --server-port ${SERVER_PORT} --server-root-path ${SERVER_ROOT_PATH} --cert-path ${CERT_PATH}"]

CMD ["./client"]