# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.26.0"
      - name: Test
        run: |
          pwd
          bash scripts/create-certs.sh all localhost
          sleep 5;
          ls
          pwd
          mkdir -p pki-go/certs/localhost/{server, client}
          pwd
          ls
          ls demo-pki/localhost/client
          ls demo-pki/localhost/server
          ls demo-pki/localhost/root
          cp demo-pki/localhost/client/* certs/localhost/client/
          cp demo-pki/localhost/server/* certs/localhost/server/
          cp demo-pki/localhost/root/* certs/localhost/server/
          cd pki-go
          pwd
          ls
          ls ./certs/localhost/client
          ls ./certs/localhost/server
          go test -v -race -coverprofile=coverage.out -covermode=atomic ./cmd/... ./internal/...
          go tool cover -html=coverage.out -o coverage.html
          go build -v ./...
  #     - name: Upload coverage to Codecov
  #       uses: codecov/codecov-action@v3
  #       with:
  #         files: pki-go/coverage.out
  #         flags: unittests
  #         name: codecov-umbrella
  #         verbose: true
  #     - name: Archive code coverage results
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: code-coverage-report
  #         path: |
  #           pki-go/coverage.out
  #           pki-go/coverage.html
  # build:
  #   needs: test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Build Server Image
  #       run: |
  #         ls
  #         pwd
  #         cd pki-go
  #         pwd
  #         docker build -f Dockerfile.server -t sirajudheenam/go-mtls-server:${{ github.sha }} .
  #     - name: Build Client Image
  #       run: docker build -f Dockerfile.client -t sirajudheenam/go-mtls-client:${{ github.sha }} .
  #     - name: Login to DockerHub
  #       if: github.ref == 'refs/heads/main'
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
  #     - name: Push Images
  #       if: github.ref == 'refs/heads/main'
  #       run: |
  #         docker push sirajudheenam/go-mtls-server:${{ github.sha }}
  #         docker push sirajudheenam/go-mtls-client:${{ github.sha }}